= [Bot] Electron 50 by Yohann Sillam
:author: nxblnd
:source-highlighter: pygments

Writeup by nxblnd (_Zenbuai-gumi_, _:wq_)

== Task

Shoperfect now has a new bug bounty program to help mitigate bot activity on their website.

You need to buy premium items from Shoperfect, but you need to be fast.

== How to solve

We can do just fine ourselves until we are required to fill the form with questions. While we are answering to them, all goods are sold!

Let\'s write a simple Python script to automate process. Using Requests lib get `/start` page. On this page there is timer, i\'ve added the same delay before accessing the next page and a random 2-5 seconds of additional delay _just in case_. We also need to get link to the next page, i\'ll use BeautifulSoup lib for that.

Move to next page: `/get_limited_item/1234` (where 1234 is random id, that we parsed with BS), and don\'t forget your cookies! This page contains the form that slows us down. Let\'s create payload for next POST request: answers to three questions, the last hidden field, and wait... What the f are "secret" and "sig" fields?

[source, html]
----
<form action="/send_offer" method="post">
    <input type="text" value="Do you like spicy potatoes ?" id="Do you like spicy potatoes ?" name="Do you like spicy potatoes ?">
    <input type="button" value="load more" id="loadmore1" onclick="load_step_1()"><br>
    <input type="text" value="Do you like sausages ?" style="visibility: hidden" id="Do you like sausages ?" name="Do you like sausages ?">
    <input type="button" value="load more" id="loadmore2" style="visibility: hidden" onclick="load_step_2()"><br>
    <input type="text" value="Are you sure ?" style="visibility: hidden" id="Are you sure ?" name="Are you sure ?">
    <input type="hidden" value="Z0FBQUFBQmhtQUdNTXVCeGpXalhWVV84WW1NZkI2bzRxd3ViWEJlZjVnNTlHejNBYjNidkU0QUJweXlXZFMyZjVVWGlBenJueFJrMHhUcWZac2ZWT3pHS3JXeXF5eElSTTQtX3NzLWtQNTRSOGpHT2E5djdsWWM9" style="visibility: hidden" id="secret" name="secret">
    <input type="hidden" value="3Z403FdB9Q0U4F0BaQ6m7h1tcQ4U5d8N3T2XeVeC5e3G8p1X8a6l0heW2V9V9864" style="visibility: hidden" id="sig" name="sig">
    <input type="submit" value="Send purchase request" id="finalPush" style="visibility: hidden">
</form>
----

There is obfuscated JS code next to the form. One line is just MD5 implementation  (no shenanigans here), and the other one creates content for `sig` field. Throw it in JS beautifier. Skipping the boring parts, let\'s review what functions are there.

[source, html]
----
<script>
    var MD5 = function(d){var r = M(V(Y(X(d),8*d.length)));return r.toLowerCase()};function M(d){for(var _,m="0123456789ABCDEF",f="",r=0;r<d.length;r++)_=d.charCodeAt(r),f+=m.charAt(_>>>4&15)+m.charAt(15&_);return f}function X(d){for(var _=Array(d.length>>2),m=0;m<_.length;m++)_[m]=0;for(m=0;m<8*d.length;m+=8)_[m>>5]|=(255&d.charCodeAt(m/8))<<m%32;return _}function V(d){for(var _="",m=0;m<32*d.length;m+=8)_+=String.fromCharCode(d[m>>5]>>>m%32&255);return _}function Y(d,_){d[_>>5]|=128<<_%32,d[14+(_+64>>>9<<4)]=_;for(var m=1732584193,f=-271733879,r=-1732584194,i=271733878,n=0;n<d.length;n+=16){var h=m,t=f,g=r,e=i;f=md5_ii(f=md5_ii(f=md5_ii(f=md5_ii(f=md5_hh(f=md5_hh(f=md5_hh(f=md5_hh(f=md5_gg(f=md5_gg(f=md5_gg(f=md5_gg(f=md5_ff(f=md5_ff(f=md5_ff(f=md5_ff(f,r=md5_ff(r,i=md5_ff(i,m=md5_ff(m,f,r,i,d[n+0],7,-680876936),f,r,d[n+1],12,-389564586),m,f,d[n+2],17,606105819),i,m,d[n+3],22,-1044525330),r=md5_ff(r,i=md5_ff(i,m=md5_ff(m,f,r,i,d[n+4],7,-176418897),f,r,d[n+5],12,1200080426),m,f,d[n+6],17,-1473231341),i,m,d[n+7],22,-45705983),r=md5_ff(r,i=md5_ff(i,m=md5_ff(m,f,r,i,d[n+8],7,1770035416),f,r,d[n+9],12,-1958414417),m,f,d[n+10],17,-42063),i,m,d[n+11],22,-1990404162),r=md5_ff(r,i=md5_ff(i,m=md5_ff(m,f,r,i,d[n+12],7,1804603682),f,r,d[n+13],12,-40341101),m,f,d[n+14],17,-1502002290),i,m,d[n+15],22,1236535329),r=md5_gg(r,i=md5_gg(i,m=md5_gg(m,f,r,i,d[n+1],5,-165796510),f,r,d[n+6],9,-1069501632),m,f,d[n+11],14,643717713),i,m,d[n+0],20,-373897302),r=md5_gg(r,i=md5_gg(i,m=md5_gg(m,f,r,i,d[n+5],5,-701558691),f,r,d[n+10],9,38016083),m,f,d[n+15],14,-660478335),i,m,d[n+4],20,-405537848),r=md5_gg(r,i=md5_gg(i,m=md5_gg(m,f,r,i,d[n+9],5,568446438),f,r,d[n+14],9,-1019803690),m,f,d[n+3],14,-187363961),i,m,d[n+8],20,1163531501),r=md5_gg(r,i=md5_gg(i,m=md5_gg(m,f,r,i,d[n+13],5,-1444681467),f,r,d[n+2],9,-51403784),m,f,d[n+7],14,1735328473),i,m,d[n+12],20,-1926607734),r=md5_hh(r,i=md5_hh(i,m=md5_hh(m,f,r,i,d[n+5],4,-378558),f,r,d[n+8],11,-2022574463),m,f,d[n+11],16,1839030562),i,m,d[n+14],23,-35309556),r=md5_hh(r,i=md5_hh(i,m=md5_hh(m,f,r,i,d[n+1],4,-1530992060),f,r,d[n+4],11,1272893353),m,f,d[n+7],16,-155497632),i,m,d[n+10],23,-1094730640),r=md5_hh(r,i=md5_hh(i,m=md5_hh(m,f,r,i,d[n+13],4,681279174),f,r,d[n+0],11,-358537222),m,f,d[n+3],16,-722521979),i,m,d[n+6],23,76029189),r=md5_hh(r,i=md5_hh(i,m=md5_hh(m,f,r,i,d[n+9],4,-640364487),f,r,d[n+12],11,-421815835),m,f,d[n+15],16,530742520),i,m,d[n+2],23,-995338651),r=md5_ii(r,i=md5_ii(i,m=md5_ii(m,f,r,i,d[n+0],6,-198630844),f,r,d[n+7],10,1126891415),m,f,d[n+14],15,-1416354905),i,m,d[n+5],21,-57434055),r=md5_ii(r,i=md5_ii(i,m=md5_ii(m,f,r,i,d[n+12],6,1700485571),f,r,d[n+3],10,-1894986606),m,f,d[n+10],15,-1051523),i,m,d[n+1],21,-2054922799),r=md5_ii(r,i=md5_ii(i,m=md5_ii(m,f,r,i,d[n+8],6,1873313359),f,r,d[n+15],10,-30611744),m,f,d[n+6],15,-1560198380),i,m,d[n+13],21,1309151649),r=md5_ii(r,i=md5_ii(i,m=md5_ii(m,f,r,i,d[n+4],6,-145523070),f,r,d[n+11],10,-1120210379),m,f,d[n+2],15,718787259),i,m,d[n+9],21,-343485551),m=safe_add(m,h),f=safe_add(f,t),r=safe_add(r,g),i=safe_add(i,e)}return Array(m,f,r,i)}function md5_cmn(d,_,m,f,r,i){return safe_add(bit_rol(safe_add(safe_add(_,d),safe_add(f,i)),r),m)}function md5_ff(d,_,m,f,r,i,n){return md5_cmn(_&m|~_&f,d,_,r,i,n)}function md5_gg(d,_,m,f,r,i,n){return md5_cmn(_&f|m&~f,d,_,r,i,n)}function md5_hh(d,_,m,f,r,i,n){return md5_cmn(_^m^f,d,_,r,i,n)}function md5_ii(d,_,m,f,r,i,n){return md5_cmn(m^(_|~f),d,_,r,i,n)}function safe_add(d,_){var m=(65535&d)+(65535&_);return(d>>16)+(_>>16)+(m>>16)<<16|65535&m}function bit_rol(d,_){return d<<_|d>>>32-_}

    (function(_0x1cfa39,_0x544e32){var _0x4bdcc3=_0x1f78,_0x1e4694=_0x1cfa39();while(!![]){try{var _0x5d8cf8=parseInt(_0x4bdcc3(0x15e))/0x1+-parseInt(_0x4bdcc3(0x171))/0x2*(-parseInt(_0x4bdcc3(0x169))/0x3)+-parseInt(_0x4bdcc3(0x173))/0x4+-parseInt(_0x4bdcc3(0x174))/0x5+-parseInt(_0x4bdcc3(0x160))/0x6+parseInt(_0x4bdcc3(0x166))/0x7+parseInt(_0x4bdcc3(0x163))/0x8*(parseInt(_0x4bdcc3(0x16b))/0x9);if(_0x5d8cf8===_0x544e32)break;else _0x1e4694['push'](_0x1e4694['shift']());}catch(_0x1ac541){_0x1e4694['push'](_0x1e4694['shift']());}}}(_0x38e9,0xd3a47));function _0x1f78(_0x11cdca,_0x76b014){var _0x38e915=_0x38e9();return _0x1f78=function(_0x1f780f,_0x191e6f){_0x1f780f=_0x1f780f-0x15e;var _0x568a3a=_0x38e915[_0x1f780f];return _0x568a3a;},_0x1f78(_0x11cdca,_0x76b014);}function _0x38e9(){var _0x55c589=['366275BkYoYe','_phantom','toString','8397GweuEM','__driver_evaluate','14237487qDPfUq','value','length','callPhantom','getElementById','secret','188xVLesg','innerWidth','5216748uspaAr','8593710WlSqic','1439974rBFoXo','__selenium_unwrapped','6176850dZafPY','min','$cdc','16HVSowp','innerHeight','webdriver'];_0x38e9=function(){return _0x55c589;};return _0x38e9();}function merge(_0x5e720a,_0x2b3fc8){var _0x39f3df=_0x1f78;out='';for(var _0x22e63e=0x0;_0x22e63e<_0x5e720a[_0x39f3df(0x16d)];++_0x22e63e){out+=_0x5e720a[_0x22e63e]+_0x2b3fc8[_0x22e63e%Math[_0x39f3df(0x161)](_0x5e720a[_0x39f3df(0x16d)],_0x2b3fc8[_0x39f3df(0x16d)])];}return out;}function create_secret(){var _0x5e8a54=_0x1f78;patterns=[_0x5e8a54(0x165),_0x5e8a54(0x16e),_0x5e8a54(0x167),'phantom','__nightmare',_0x5e8a54(0x16a),_0x5e8a54(0x15f),_0x5e8a54(0x162)];var _0x571f6e='';for(pattern of patterns){if(navigator[pattern]!=null)_0x571f6e+=navigator[pattern]['toString']()[0x0];else window[pattern]!=null&&(_0x571f6e+=window[pattern][_0x5e8a54(0x168)]()[0x0]);}_0x571f6e+=(window[_0x5e8a54(0x172)]<0x3e8)[_0x5e8a54(0x168)]()[0x0],_0x571f6e+=(window[_0x5e8a54(0x164)]<0x1f4)[_0x5e8a54(0x168)]()[0x0],document[_0x5e8a54(0x16f)]('sig')[_0x5e8a54(0x16c)]=merge(MD5(_0x571f6e),document[_0x5e8a54(0x16f)](_0x5e8a54(0x170))[_0x5e8a54(0x16c)]);}create_secret();
</script>
----

One returns array of strings. Other called after creation and cycle shifts that array until strings are in place. There is function that allows to get strings from the array like it is indexed from 350. `create_secret()` does some checks about browser (mostly if it is automated), all you need to know is that it should create string `fff` (`window.innerHeight` >= 500, `window.innerWidth` >= 1000 and `navigator.webdriver` is disabled). This string is hashed with MD5 and passed in some `merge()` function with `secret` token from page. Algorithm is pretty simple, and you can see it in my solution below.

[source, python]
----
import requests
from bs4 import BeautifulSoup as bs
import time
import random
from hashlib import md5

host = 'https://electron.chal.intentsummit.org/'
headers = {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0'}

def merge(hash_val, secret):
    res = ''
    hash_len = len(hash_val)
    secret_len = len(secret)
    for i, char in enumerate(hash_val):
        res += char + secret[i % min(hash_len, secret_len)]
    return res

# /start
start = requests.get(f'{host}/start', {'id': 1}, headers=headers, verify=False)
soup = bs(start.text, 'html.parser')
id = int(soup.find(id='start_purchase')['href'].split('/')[-1])
id = id // 2 if id % 2 == 0 else id * 3 + 1
time.sleep(60 + random.randint(2, 5))

# /get_limited_item
get_limited_item = requests.get(f'{host}/get_limited_item/{id}', cookies=start.cookies, headers=headers, verify=False)
soup = bs(get_limited_item.text, 'html.parser')
secret = soup.find(id='secret')['value']

# /send_offer
payload = {
    'Do you like spicy potatoes ?': 'No',
    'Do you like sausages ?': 'No',
    'Are you sure ?': 'Yes',
    'secret': secret,
    'sig': merge(md5('fff'.encode()).hexdigest(), secret),
    'finalPush': 'Send purchase request'
}
send_offer = requests.post(f'{host}/send_offer', data=payload, cookies=get_limited_item.cookies, headers=headers, verify=False)

print(send_offer.text)
----

Though site is kinda picky, and may reject your requests, so wait a little and try again.
